### ISSUE TITLE
Crash on Android 6 and 7, java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;

### ISSUE THREAD

**Issue by maartenvgpersgroep** [SourcePointUSA/android-cmp-app#593]
**Describe the bug**

This issue seems very similar to https://github.com/SourcePointUSA/android-cmp-app/issues/575, but this issue exists in the latest version of the library at this time (7.0.4).
We see quite some crashes coming in, after updating from 6.x.x to the latest 7.0.4 version of the CMP library, with the following stacktrace:

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/format/DateTimeFormatter;
       at com.sourcepoint.cmplibrary.consent.ConsentManagerUtilsImpl$$InternalSyntheticApiModelOutline$1$35912cd33316260773abedddf90abf8f75b0a9d183d42e858616e0113f27df83$0.m(ConsentManagerUtilsImpl.java:3)
       at com.sourcepoint.cmplibrary.consent.ConsentManagerUtilsImpl.updateGdprConsentOptimized(ConsentManagerUtils.kt:135)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:167)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:138)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.invoke$lambda-0(ExecutorManager.kt:37)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.$r8$lambda$YcU9LB-LQlcZOnRwBNhL6k0AYg0(ExecutorManager.kt:1)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1$$InternalSyntheticLambda$1$270b46b0f6bf75c77303e1f25d99cf384b0205b066c32f1b52d0c4bc82f1eb7d$0.run(ExecutorManagerImpl.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.format.DateTimeFormatter" on path: DexPathList[[zip file "/data/app/xxx/base.apk", zip file "/data/app/xxx/split_config.nl.apk", zip file "/data/app/xxx-1/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/xxx-1/lib/arm64, /system/lib64, /vendor/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.sourcepoint.cmplibrary.consent.ConsentManagerUtilsImpl$$InternalSyntheticApiModelOutline$1$35912cd33316260773abedddf90abf8f75b0a9d183d42e858616e0113f27df83$0.m(ConsentManagerUtilsImpl.java:3)
       at com.sourcepoint.cmplibrary.consent.ConsentManagerUtilsImpl.updateGdprConsentOptimized(ConsentManagerUtils.kt:135)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:167)
       at com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke(ServiceImpl.kt:138)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.invoke$lambda-0(ExecutorManager.kt:37)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.$r8$lambda$YcU9LB-LQlcZOnRwBNhL6k0AYg0(ExecutorManager.kt:1)
       at com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1$$InternalSyntheticLambda$1$270b46b0f6bf75c77303e1f25d99cf384b0205b066c32f1b52d0c4bc82f1eb7d$0.run(ExecutorManagerImpl.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

** About your environment **
 - Target + Compile SDK version 33, our minimum SDK version is 23
 - The problem happens on devices with SDK version 23 through 25
 - Device: LG Nexus 5X, Huawei MediaPad T3 10, Samsung Galaxy Tab S2
 - OS: Android 6, Android 7

**To Reproduce**
- Accept all cookies in the cookie wall, the first run everything works as expected
- Close the app (force close just to be sure)
- Re-open the app and initialize the sdk again
- The app will crash.

**Additional context**

The problem seems to be caused by using classes from the `java.time` package, which are only supported on API 26 and up. I suppose we could use java 8 desugaring or something like ThreeTenABP, but we'd prefer to consume a library that supports API 23 - 25 out of the box.

**Comment by gmorales** [comment]
We're facing the same issue in our project. We're using version 7.0.4 and affecting also APIs 23 - 25.

````java
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Ljava/time/format/DateTimeFormatter;
com.sourcepoint.cmplibrary.consent.ConsentManagerUtilsImpl$$InternalSyntheticApiModelOutline$1$35912cd33316260773abedddf90abf8f75b0a9d183d42e858616e0113f27df83$0.m (ConsentManagerUtilsImpl.java:4)
com.sourcepoint.cmplibrary.consent.ConsentManagerUtilsImpl.updateGdprConsentOptimized (ConsentManagerUtils.kt:135)
com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke (ServiceImpl.kt:167)
com.sourcepoint.cmplibrary.data.ServiceImpl$getMessages$1.invoke (ServiceImpl.kt:138)
com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.invoke$lambda-0 (ExecutorManager.kt:37)
com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$executeOnWorkerThread$1.$r8$lambda$YcU9LB-LQlcZOnRwBNhL6k0AYg0 (ExecutorManager.kt:1)
com.sourcepoint.cmplibrary.core.ExecutorManagerImpl$$InternalSyntheticLambda$1$27def0c3b3044e9ae8d04c3a005a444396a2c592f72e8cfb5bbf7ae886356bb2$0.run$bridge (ExecutorManagerImpl.java:13)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:762)
````

Is there some ETA for a fix or should we revert the version for now?

**Comment by maartenvgpersgroep** [comment]
@gmorales If the issue is pressing, we have found that enabling desugaring works as a temporary solution: https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by carmelo-iriti** [comment]
Hi @maartenvgpersgroep and @gmorales, 

thanks for the message. We just released the v7.0.6 which fixes this issue, it will be available on maven Central in a couple of hours.

**Comment by carmelo-iriti** [comment]
Hi @maartenvgpersgroep and @gmorales,

let me know if I can close this issue  👍🏻

**Comment by maartenvgpersgroep** [comment]
Hi @carmelo-iriti, I can confirm that the latest build seems to work on Android 6 and 7. Thank you for the quick response!

**Comment by gmorales** [comment]
@carmelo-iriti I tested version 7.0.6 in a phone with API 24 removing the desugar library and its configuration and it worked fine!

**Comment by carmelo-iriti** [comment]
Thanks guys!
